---
version: "3"
services:
  train:
    image: madhavikollya/dockerprojecttrain:latest
    ports:
      - "80:80"
    deploy:  
      replicas: 2
  dth:
    image: madhavikollya/dockerprojectdth:latest
    ports:
      - "81:80"
    deploy:  
      replicas: 2
  movies:
    image: madhavikollya/dockerprojectmovies:latest
    ports:
      - "82:80"
    deploy:  
      replicas: 2
  recharge:
    image: madhavikollya/dockerprojectrecharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 2
